### ISSUE TITLE
Gravar áudio pelo aplicativo

### ISSUE THREAD

**Issue by nameforjoy** [nameforjoy/Memoria#16]
- Consertar o xib
- Resolver o problema de arrastar a barrinha do áudio (desabilitando ou consertando)
- Pedir a permissão de acesso ao microfone só na hora de gravar
- Animação de feedback visual para enquanto o áudio estiver sendo gravado

**Comment by lumagabino** [comment]
Links que podem ajudar:
https://iosexample.com/a-customizable-audio-visualization-component-that-works-with-recording/
https://github.com/agilie/DisPlayers-Audio-Visualizers
https://cocoapods.org/pods/EZAudio
